<?php

test('renders the Project Cham homepage', function () {
    $response = $this->get(route('home'));

    $response
        ->assertViewIs('pages.home')
        ->assertSeeText('Supporting Children Battling Cancer with Care, Structure, and Measurable Impact.')
        ->assertSeeText('Awareness & Advocacy')
        ->assertSeeText('Child & Family Support')
        ->assertSeeText('Access to Care')
        ->assertSeeText('Support that reaches the child—and strengthens the family.')
        ->assertSeeText('Awareness that leads to informed action')
        ->assertSeeText('Impact that stays visible and measurable')
        ->assertSeeText('Three ways we turn support into real impact.')
        ->assertSeeText('Driving awareness to promote early detection and informed action.')
        ->assertSeeText('Connecting families to treatment partners and the critical resources they need.')
        ->assertSeeText('Progress built around better outcomes.')
        ->assertSeeText('Awareness that leads to earlier action')
        ->assertSeeText('Care connections that reduce the distance')
        ->assertSeeText('Moments of care. Stories in motion.')
        ->assertSeeText('A closer look at the people, conversations, and care connections turning structured support into everyday progress for children and families.')
        ->assertSeeText('Room to learn, laugh, and still feel like a child')
        ->assertSeeText('Knowledge shared before care is urgent')
        ->assertSeeText('A clearer way into care')
        ->assertSeeText('Collective effort creates lasting support.')
        ->assertSeeText('Partner With Us')
        ->assertSeeText('Support a Child')
        ->assertSeeText('Use Your Voice')
        ->assertSeeText('Gather, learn, and help move care forward.')
        ->assertSeeText('Childhood Cancer Awareness Session')
        ->assertSeeText('Care Access Partner Clinic')
        ->assertSeeText('10:00 AM')
        ->assertSeeText('14 Sep, 2026')
        ->assertSeeText('Lagos, Nigeria')
        ->assertSeeText('The people behind every act of care.')
        ->assertSeeText('Amara Okafor')
        ->assertSeeText('Child & Family Support Lead')
        ->assertSeeText('Community Outreach Coordinator')
        ->assertSeeText('Care families can feel and remember.')
        ->assertSeeText('A Project Cham family')
        ->assertSeeText('Identity protected')
        ->assertSeeText('Help every child reach care and possibility.')
        ->assertSeeText('Project Cham is built on one goal: to ensure that every child battling cancer receives the support, care, and opportunity needed to survive and thrive.')
        ->assertSeeText('Get involved')
        ->assertSeeText('Read stories that move care forward.')
        ->assertSeeText('When Awareness Becomes Early Action')
        ->assertSeeText('What Families Need Between Hospital Visits')
        ->assertSeeText('Understanding Childhood Cancer Warning Signs')
        ->assertSeeText('Turning Advocacy Into Measurable Impact')
        ->assertSeeText('Follow the work moving care forward.')
        ->assertSeeText('Quick links')
        ->assertSeeText('Start a conversation')
        ->assertSee('Project Cham on Facebook')
        ->assertSee('Project Cham on Instagram')
        ->assertSee('Project Cham on X');
});
