<?php

test('renders the Project Cham homepage', function () {
    $response = $this->get(route('home'));

    $response
        ->assertViewIs('pages.home')
        ->assertSeeText('No Child Should Face Cancer Alone.')
        ->assertSeeText('Awareness & Early Action')
        ->assertSeeText('Treatment & Care Support')
        ->assertSeeText('Family & Psychosocial Support')
        ->assertSeeText('Research & Advocacy')
        ->assertSeeText('Support that reaches the child—and strengthens the family.')
        ->assertSeeText('Awareness & early detection education for communities')
        ->assertSeeText('Four strategic pillars advancing childhood cancer care.')
        ->assertSeeText('Project CHAM in Numbers.')
        ->assertSeeText('100+')
        ->assertSeeText('Children Reached')
        ->assertSeeText('70+')
        ->assertSeeText('Families Supported')
        ->assertSeeText('Moments of care. Stories in motion.')
        ->assertSeeText('A closer look at the people, conversations, and care connections turning structured support into everyday progress for children and families.')
        ->assertSeeText('Room to learn, laugh, and still feel like a child')
        ->assertSeeText('Knowledge shared before care is urgent')
        ->assertSeeText('A clearer way into care')
        ->assertSeeText('Collective effort creates lasting support.')
        ->assertSeeText('Partner With Us')
        ->assertSeeText('Support a Child')
        ->assertSeeText('Use Your Voice')
        ->assertSeeText('Gather, learn, and help move care forward.')
        ->assertSeeText('Childhood Cancer Awareness Session')
        ->assertSeeText('Care Access Partner Clinic')
        ->assertSeeText('10:00 AM')
        ->assertSeeText('14 Sep, 2026')
        ->assertSeeText('Lagos, Nigeria')
        ->assertSeeText('The people behind every act of care.')
        ->assertSeeText('Care families can feel and remember.')
        ->assertSeeText('A Project Cham family')
        ->assertSeeText('Identity protected')
        ->assertSeeText('No child should face cancer alone.')
        ->assertSeeText('Project CHAM is built on one conviction: to ensure that every child battling cancer receives the support, care, and opportunity needed to survive and thrive.')
        ->assertSeeText('Read guides & stories that move care forward.')
        ->assertSeeText('When Awareness Becomes Early Action')
        ->assertSeeText('What Families Need Between Hospital Visits')
        ->assertSeeText('Understanding Childhood Cancer Warning Signs')
        ->assertSeeText('Turning Advocacy Into Measurable Impact')
        ->assertSeeText('Follow the work moving care forward.')
        ->assertSeeText('Quick links')
        ->assertSeeText('Start a conversation')
        ->assertSee('Project Cham on Facebook')
        ->assertSee('Project Cham on Instagram')
        ->assertSee('Project Cham on X');
});
